name: Push Event Workflow

on:
  push:  # push request on 'develop'
    branches:
    - develop
    
  pull_request: # pull request with target main
    branches:
    - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Packages 
      run : pip install ug4py-base matplotlib ipython pyvista nbformat trame ipywidgets unittest-xml-reporting
      
    - name : Run tests 
      run : |
        python -m unittest tests/integration/test_solvers.py 
        ls
        cd $HOME
        ls
    - name : Upload test artifacts 
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: unittest-artifacts
        path: test-reports
    - uses: test-summary/action@v2
      with:
        paths: "test-reports/TEST-*.xml"

    #- name: Push to main
    #  if: success()
    #  run: |
    #    ls
    #    git config --global user.name 'github-actions[bot]'
    #    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #    git checkout main
    #    git merge develop
    #    git push origin main
